version: '3.8'

services:
  outlook-node:
    build:
      context: ./containers/node
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    volumes:
      - .\containers\node\lib:/app/lib

  nginx:
    build:
      context: ./containers/nginx
      dockerfile: Dockerfile
    ports:
      - "3000:443"
    depends_on:
      - outlook-node
    volumes:
      - ./containers/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./containers/nginx/nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt
      - ./containers/nginx/nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key
